name: Deploy to Azure Functions(python)

on:
  push:
    branches:
    - main


env:
  AZURE_WEBAPP_NAME: function-app-test3


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.10 environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build web app
      uses: azure/appservice-build@v2
    - name: Deploy to Azure functions
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.TEST3_PUBLISH_PROFILE }}
        package: .
